config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'tags/:tag', to: 'articles#index', as: :tag
  get 'sessions/create'
  get 'sessions/destroy'
  root 'articles#index'
  resources :articles,  param: :slug do
    resources :comments
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :taggings
    has_many :tags, through: :taggings
    belongs_to :user, optional: true

    def to_param
        slug
    end

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end

    def self.find_with_tag(tag)
        sql = "
                select * from articles 
                inner join taggings t on articles.id = t.article_id 
                inner join tags t2 on t.tag_id = t2.id
                where t2.name = '#{tag}'
            "
        self.find_by_sql(sql)
    end

    def self.tag_counts 
        Tag.select("tags.*, count(taggings.tag_id) as count").
        joins(:taggings).group("taggings.tag_id")
    end
    
    def all_tags
        self.tags.map(&:name)
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :articles, optional: true
    
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles , through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :tag, optional: true
end

app/models/user.rb
class User < ApplicationRecord

    has_many :comments, dependent: :destroy
    

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
          user.provider = auth.provider
          user.uid = auth.uid
          user.email = auth.info.email
          user.icon = auth.info.image
          user.name = auth.info.name
          user.oauth_token = auth.credentials.token
          user.oauth_expires_at = Time.at(auth.credentials.expires_at)
          user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    layout 'article', only: [:index]
    

    def index
        if params[:tag]
            @articles = Article.find_with_tag(params[:tag])
        else
            @articles = Article.all     
        end
    end

    def new
    end

    def edit
        @article = Article.find_by(slug: params[:slug])
    end
    def destroy
        @article = Article.find_by(slug: params[:slug])
        @article.destroy
        
        redirect_to articles_path
        
    end
    def update
        @article = Article.find_by(slug: params[:slug])
        if(@article.update(article_params))
            redirect_to article_path(@article.slug)
        end
        
    end

    def create
        @article = Article.new(article_params)
        @article.save
        redirect_to articles_path(@article.slug)
    end

    def show 
        @article = Article.find_by(slug: params[:slug])
        @comments = Comment.where("article_id=?",params[:slug])
        session[:article] = @article.id
        respond_to do |format|
            format.html {render :layout => 'article_show'}
        end
    end

    private
        def article_params
            params.require(:article).permit(:title, :slug, :subtitle, :body, :all_tags)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create 
        @article = Article.find(params[:article_id])       
        @comment = @article.comments.build(comment_params)
        @comment.user_id = current_user.id
        @comment.article_id = @article.id
        if @comment.save 
            redirect_to @article
        else
            redirect_to  @article, notice: "did not comment!"
        end
    end

    def destroy 
    end
    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to article_path(session[:article])
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def profile
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 
    def markdown(text)
        renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
        options = {
            autolink: true,
            no_intra_emphasis: true,
            disable_indented_code_blocks: true,
            fenced_code_blocks: true,
            lax_html_blocks: true,
            strikethrough: true,
            superscript: true,
            disable_indented_code_blocks: true,
            highlight: true,
            quote: true
        }

        Redcarpet::Markdown.new(renderer, options).render(text).html_safe       
    end

    def emojify(content)
        content.to_str.gsub(/:([\w+-]+):/) do |match|
            %(<i class="twa twa-lg twa-#{$1}"></i>)
        end.html_safe if content.present?
      end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_with(model: @article, local:true) do |form| %>
<p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :slug %> <br>
    <%= form.text_area :slug%>
</p>

<p>
    <%= form.label :subtitle %> <br>
    <%= form.text_area :subtitle%>
</p>

<p>
    <%= form.label :body %> <br>
    <%= form.text_area :body %>
</p>
<p> 
    <%= form.label :all_tags %> <br>
    <%= form.text_field :all_tags %>
</p>
<p>
    <%= form.submit %>
</p>
<% end%>

<%= link_to 'back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<a href="<%= article_path(article.slug)%>" class="side-project w-inline-block">
    <div class="side-project__info">
        <div class="side-project__date"><%= article.created_at %></div>
        <div class="side-project__status live">Live</div>
    </div>
    <h2 class="side-project__title"><%= article.title %></h2>
    <p class="side-project__description"><%= article.subtitle %></p>
    <div class="side-project__circle"></div>
</a> 
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with scope: :article, url: articles_path,  local: true do |form| %>
<p>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :slug %> <br>
    <%= form.text_field :slug %>
</p>

<p>
    <%= form.label :subtitle %> <br>
    <%= form.text_area :subtitle%>
</p>
<p>
    <%= form.label :body %> <br>
    <%= form.text_area :body %>
</p>
<p> 
    <%= form.label :all_tags %> <br>
    <%= form.text_field :all_tags %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<h2 class="side-project__title">
    <%= @article.title %>
</h2>
    <p class="side-project__date">June 2017</p>
    <div class="tag">
        <%= raw @article.all_tags.map { |t| link_to t, tag_path(t)}.join(', ') %> 
     
    </div>                
<p class="side-project__description">
    <%= emojify markdown @article.body %>
</p>


<!-- 
<p>
    <strong>Tags:</strong>
</p> -->


<!-- <%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'back', articles_path %> 



<div>
    <% if current_user %>
      <h2>Comments</h2>
      <%= form_with(model: [@article, @article.comments.build]) do |f| %>
        <%= f.text_area :content, placeholder: "write comments here" %>
        <br>
        <%= f.submit "enter", class: "btn btn-primary" %>
      <% end %>
    <% else %>
    
        <%= link_to "Bình loạn", "/auth/google_oauth2" %>
    <% end %>    
</div> -->


<!-- <hr>
<% @comments.each do |comment| %>
  <h5>
      <strong><%= comment.user.name %></strong> wrote <small>  <%= time_ago_in_words(comment.created_at)  %></small>
  </h5>
  <h3>
      <%= comment.content %>
  </h3>
<% end %>
 -->

<script>hljs.initHighlightingOnLoad();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nhaphan</title>

    <meta name="google-signin-client_id" content="936823825836-7mqo8571ps8u2rq94qus1nj3u687k3id.apps.googleusercontent.com">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="http://ellekasai.github.io/twemoji-awesome/twemoji-awesome.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= yield %>
    </div>
   
  </body>
</html>

app/views/layouts/article.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
        <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>dit con me</title>
    <%= stylesheet_link_tag   'main' %>
</head>

<body class="bg-pattern">
    <div class="main_content">
        <div class="social-links__wrapper">
            <a href="https://www.instagram.com/kalipts98" target="_blank" class="social-link">Instagram</a>
            <a href="https://twitter.com/NHAPHAN4" target="_blank" class="social-link">Twitter</a>
            <a href="https://www.facebook.com/kalipts" target="_blank" class="social-link">Facebook</a>
        </div>
        <div class="avatar__mobile"></div>
        <h1>Chào, Mình là <strong>Nhã</strong>. designer  Một chàng trai với chiếc bụng gần phệ, rốn không lồi,
             khuôn mặt luôn tỏ vẻ tư lự, trên thông thiên văn, dưới tường địa lý,
                có tinh thần yêu nước nồng nàn
        </h1>
        <div class="side-projects__wrapper"></div>
        
          <%= yield %>
                        
        </div>
    </div>
    <div class="avatar">
    </div>
</body>
</html>

app/views/layouts/article_show.html.erb
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <title>xin chao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'show' %>
</head>

<body class="bg-pattern">
    <div class="main_content">
        <div class="social-links__wrapper">
            <a href="" class="social-link">Home</a>
        </div>
        <%= yield %>
    </div>
   
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Xin chào, rails</h1>
</body>
</html>